
sudo: false

matrix:
  include:
    - name: "Hemin Engine"
      language: scala
      env: 
        - ISOLATED=true
      scala: 2.12.6
      jdk:
        - oraclejdk8
        - openjdk8
#      elm: # clear
#      node_js: # clear
      services:
        - docker
      before_install:
        - docker-compose -f docker-compose.yml up -d
      before_script:
        - cd engine
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean test

    - name: "Hemin API"
      language: scala
      env: 
        - ISOLATED=true
      scala: 2.12.6
      jdk:
        - oraclejdk8
        - openjdk8
#      elm: # clear
#      node_js: # clear
      cache:
        directories:
          - $HOME/.m2
      services:
        - docker
      before_install:
        - docker-compose -f docker-compose.yml up -d
      install: 
        - cd engine
        - sbt clean compile publishM2  
        - cd ..
      before_script:
        - cd api
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean test

    - name: "Hemin WebApp"
      language: elm
      env: 
        - ISOLATED=true
      elm: elm0.19.0
      node_js: '10' # latest 10.x
#      scala: # clear
#      jdk: # clear
      cache:
        directories:
          - tests/elm-stuff/build-artifacts
          - sysconfcpus

      before_install:
        - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
          if [ ! -d sysconfcpus/bin ];
          then
            git clone https://github.com/obmarg/libsysconfcpus.git;
            cd libsysconfcpus;
            ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
            make && make install;
            cd ..;
          fi
      install:
        - npm install -g elm@0.19.0-bugfix2 elm-test elm-format create-elm-app
        - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-old
        - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm with sysconfcpus -n 1"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 1 elm-old "$@"' > $(npm config get prefix)/bin/elm
        - chmod +x $(npm config get prefix)/bin/elm
        - cd tests
        - npm install
        - cd ..
      before_script:
        - cd webapp
      script:
        - elm-format --validate src/
        - elm-app test