
sudo: false

matrix:
  include:
    - env: PROJECT=hemin-engine
      language: scala
      scala:
        - 2.12.6
      jdk:
        - oraclejdk8
        - openjdk8
      script:
        - sbt test

    - env: PROJECT=hemin-api
      language: scala
      scala:
        - 2.12.6
      jdk:
        - oraclejdk8
        - openjdk8
      install: cd hemin-engine && sbt clean compile publishM2  
      cache:
        directories:
          - $HOME/.m2
      #before_script:
      #  - cd hemin-api
      script:
        - sbt test

    - env: PROJECT=hemin-web/beta
      language: elm
      cache:
        directories:
          - tests/elm-stuff/build-artifacts
          - sysconfcpus

      before_install:
        - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
          if [ ! -d sysconfcpus/bin ];
          then
            git clone https://github.com/obmarg/libsysconfcpus.git;
            cd libsysconfcpus;
            ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
            make && make install;
            cd ..;
          fi
      install:
        - npm install -g elm@0.19.0-bugfix2 elm-test elm-format create-elm-app
        - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-old
        - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm with sysconfcpus -n 1"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 1 elm-old "$@"' > $(npm config get prefix)/bin/elm
        - chmod +x $(npm config get prefix)/bin/elm
        - cd tests
        - npm install
        - cd ..
      #before_script:
      #  - cd hemin-web/beta
      script:
        - elm-format --validate src/
        - elm-app test