language: scala

scala:
  - 2.12.6
#  - 2.11.8

jdk:
  - oraclejdk8
  - openjdk8

sudo: false

install: cd engine && sbt clean compile publishM2

cache:
  directories:
    - $HOME/.m2
    - $HOME/travis/.embedmongo

env: 
  - PROJECT=engine
  - PROJECT=api

#matrix:
#    include:
#        - env: PROJECT=engine
#        - env: PROJECT=api

script: 
#  - cd $PROJECT 
  - sbt test
#script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then echo "$PROJECT is being built"; else echo "$PROJECT is NOT being built"; fi