version: '2'
services:
    mongo:
        image: mongo:4.1
        container_name: "hemin-mongo"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        #  - MONGODB_USER="user" 
        #  - MONGODB_PASS="pass"
        volumes:
            - ./data/mongo:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet
#    mongo-express:
#        image: mongo-express:latest
#        container_name: "mongo-express"
#        ports:
#            - 8081:8081
#        links:
#            - mongodb