version: '2'
services:
  neo4j:
    image: neo4j:3.5.3
    container_name: "hemin-neo4j"
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs